name: Deploy Python App via Docker Compose

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted 
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version
          
      - name: Deploy with Docker Compose
        run: |
          docker-compose pull
          docker-compose up -d --remove-orphans 