name: Deploy Python App via Docker Compose

on:
  workflow_run:
    workflows: ["Python application"]
    types:
      - completed
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted 
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
          
      - name: Deploy with Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
